-- Inserimento dati demo per il calendario con tipi corretti
INSERT INTO public.initiatives (
  title, 
  description, 
  location, 
  date, 
  end_date,
  type, 
  organization, 
  participants, 
  contact, 
  published,
  is_generated
) VALUES 
-- Iniziative correnti (Gennaio 2025)
(
  'Corso di Programmazione per Principianti',
  'Un corso introduttivo alla programmazione rivolto a chi vuole avvicinarsi al mondo del coding. Imparerai i fondamenti di Python e creerai il tuo primo progetto.',
  'Centro Digitale Milano, Via Roma 15',
  '2025-01-15T09:00:00Z',
  '2025-01-20T17:00:00Z',
  'l2',
  'TechForAll Milano',
  '25 partecipanti max',
  'info@techforall.it',
  true,
  true
),
(
  'Pulizia del Parco Lambro',
  'Giornata di volontariato per la pulizia e manutenzione del Parco Lambro. Porta guanti e vestiti comodi!',
  'Parco Lambro, ingresso Via Feltre',
  '2025-01-18T08:30:00Z',
  '2025-01-18T13:00:00Z',
  'social',
  'EcoVolontari Milano',
  'Tutti benvenuti',
  'parcolambro@ecovolontari.org',
  true,
  false
),
(
  'Festival della Musica Classica',
  'Tre serate dedicate alla musica classica con orchestra sinfonica e solisti internazionali.',
  'Teatro alla Scala, Milano',
  '2025-01-22T20:30:00Z',
  '2025-01-24T23:00:00Z',
  'cultura',
  'Fondazione Teatro alla Scala',
  '2000 posti disponibili',
  'biglietteria@teatroallascala.org',
  true,
  false
),
-- Iniziative future (Febbraio-Marzo 2025)
(
  'Torneo di Calcetto Solidale',
  'Torneo di calcetto a 5 per raccogliere fondi per la mensa dei bambini. Iscrizioni aperte fino al 10 febbraio.',
  'Centro Sportivo Corvetto',
  '2025-02-15T14:00:00Z',
  '2025-02-15T19:00:00Z',
  'sport',
  'Polisportiva Corvetto',
  '16 squadre',
  'tornei@polisportivacorvetto.it',
  true,
  false
),
(
  'Workshop AI e Creatività',
  'Scopri come lartificial intelligence può potenziare la tua creatività. Workshop pratico con strumenti AI per arte e design.',
  'Spazio Innovazione, Via Brera 8',
  '2025-02-28T15:00:00Z',
  '2025-02-28T18:00:00Z',
  'l2',
  'Innovation Hub Milano',
  '30 partecipanti',
  'workshop@innovationhub.mi',
  true,
  true
),
(
  'Mercatino del Libro Usato',
  'Mercatino solidale per scambio e vendita di libri usati. Il ricavato andrà alla biblioteca di quartiere.',
  'Piazza Sant Alessandro',
  '2025-03-08T09:00:00Z',
  '2025-03-08T17:00:00Z',
  'cultura',
  'Biblioteca Comunale Porta Venezia',
  'Libero accesso',
  'bibliotecapv@comune.milano.it',
  true,
  false
),
(
  'Corso di Cucina Vegetariana',
  'Impara a cucinare piatti vegetariani deliziosi e nutrienti con chef professionisti.',
  'Scuola di Cucina Verde, Via Navigli 22',
  '2025-03-12T18:30:00Z',
  '2025-03-19T21:00:00Z',
  'social',
  'Associazione Cuochi Sostenibili',
  '12 posti disponibili',
  'corsi@cuochisostenibili.org',
  true,
  false
),
-- Iniziative passate (per mostrare funzionalità "terminata")
(
  'Hackathon per il Sociale 2024',
  'Maratona di programmazione per sviluppare soluzioni innovative per problemi sociali della città.',
  'Università Bocconi, Aula Magna',
  '2024-12-15T09:00:00Z',
  '2024-12-16T18:00:00Z',
  'l2',
  'Milano Digital Innovation',
  '100 sviluppatori',
  'hackathon@milanodigital.it',
  true,
  true
),
(
  'Concerto di Natale Benefico',
  'Concerto del coro cittadino per raccogliere fondi per le famiglie in difficoltà durante le festività.',
  'Chiesa di Santa Maria delle Grazie',
  '2024-12-20T21:00:00Z',
  '2024-12-20T23:00:00Z',
  'cultura',
  'Coro Cittadino Milano',
  '300 posti',
  'concerto@coromilano.it',
  true,
  false
),
-- Iniziative con date diverse per testare il calendario
(
  'Corso di Yoga nel Parco',
  'Sessioni di yoga allaria aperta per rilassarsi e ritrovare il benessere psicofisico.',
  'Parco Sempione, area fitness',
  '2025-04-05T07:00:00Z',
  '2025-04-05T08:30:00Z',
  'social',
  'Benessere Milano',
  '20 partecipanti',
  'yoga@benesseremilano.it',
  true,
  false
),
(
  'Conferenza Innovazione Sostenibile',
  'Incontro con esperti internazionali su tecnologie pulite e sviluppo sostenibile.',
  'Palazzo delle Stelline, Sala Conferenze',
  '2025-04-18T14:30:00Z',
  '2025-04-18T18:00:00Z',
  'social',
  'Milano Green Innovation',
  '150 partecipanti',
  'conferenza@milanogreenin.org',
  true,
  true
),
(
  'Laboratorio di Ceramica per Bambini',
  'Corso di ceramica creativa per bambini dai 6 ai 12 anni. Materiali inclusi.',
  'Atelier Creativi, Via Garibaldi 45',
  '2025-05-10T15:00:00Z',
  '2025-05-10T17:00:00Z',
  'cultura',
  'Arte per Bambini Milano',
  '15 bambini max',
  'laboratori@artebambini.mi',
  true,
  false
),
-- Iniziative aggiuntive per arricchire il calendario
(
  'Maratona di Milano 2025',
  'La tradizionale maratona cittadina con percorso di 42km attraverso i monumenti storici.',
  'Partenza da Corso Venezia',
  '2025-04-27T08:00:00Z',
  '2025-04-27T15:00:00Z',
  'sport',
  'Marathon Milano Organization',
  '45000 corridori',
  'info@milanmarathon.it',
  true,
  false
),
(
  'Festival del Cinema Indipendente',
  'Rassegna di film indipendenti con proiezioni e incontri con registi emergenti.',
  'Cinema Beltrade, Via Oxilia 10',
  '2025-06-12T19:00:00Z',
  '2025-06-16T23:30:00Z',
  'cultura',
  'Associazione Cinema Nuovo',
  '200 posti per serata',
  'festival@cinematuovo.org',
  true,
  false
),
(
  'Giornata dello Sport Inclusivo',
  'Evento dedicato allo sport per persone con disabilità con dimostrazioni e prove pratiche.',
  'Palazzetto dello Sport, Via dei Ciclamini',
  '2025-09-15T10:00:00Z',
  '2025-09-15T18:00:00Z',
  'sport',
  'Comitato Paralimpico Milano',
  'Accesso libero',
  'inclusivo@paralimpico.mi',
  true,
  false
);